[package]
name = "cloudflare-ingress-controller-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
k8s-openapi = { version = "0.24.0", features = ["latest"] }
kube = { version = "0.98.0", features = ["runtime", "derive"] }
tokio = { version = "1.42.0", features = ["full"] }
